### PR TITLE
upgrade strimzi to version 0.20

### PR DESCRIPTION
**Pull request by runeanielsen**
Upgrade strimzi to 0.20. The upgrade requires uninstalling the current strimzi operator (which will take down all kafka resources). After install the kafka operator and do a helm upgrade to support the changes in the KafkaCluster custom type.

### CODE REVIEW

**Comment by runeanielsen** [comment]
This is on hold because there are issues with upgrading existing Strimzi 0.19 to 0.20. The reason is because that the new version of Strimzi uses Helm 3.0, and it will therefore delete the existing cluster resulting in maybe data loss and full downtime.

**Comment by runeanielsen** [comment]
https://github.com/strimzi/strimzi-kafka-operator/issues/3877

**Comment by runeanielsen** [comment]
There will still be issues, even with the workaround, since the CRD won't be updated to support the new way to define listeners as shown below. So a way to update the existing CRD needs to be done.

```yaml
listeners:
  - name: local
    port: 9092
    type: internal
    tls: true
  - name: external1
    port: 9093
    type: loadbalancer
    tls: true
  - name: external2
    port: 9094
    type: nodeport
    tls: true
```

**Comment by IlyaNakhaichuk** [comment]
@runeanielsen, maybe there is a solution to update crd, after updating from version 0.19 to 0.20 without data loss?

**Comment by runeanielsen** [comment]
Hi @IlyaNakhaichuk, this issue is currently on hold, but hopefully there is a way to upgrade the crd without data loss, but I haven't had time to look much into it since we're currently very busy with new features.

Do you have any experience upgrading, from 0.19 to 0.20?

**Comment by runeanielsen** [comment]
@IlyaNakhaichuk that is the issue I also had when I tried it, I'll let you know if I figure out a way to handle it when I get the time.

**Comment by IlyaNakhaichuk** [comment]
Hi @runeanielsen  Maybe you already got something when you upgrade from version 19 to version 20 of the strimzi operator?

**Comment by runeanielsen** [comment]
@IlyaNakhaichuk not yet, haven't had the time. I found this the other day https://github.com/helm/helm-2to3, that would be the first thing I would try when I got the time.

**Comment by IlyaNakhaichuk** [comment]
@runeanielsen 
Hi.
I tried to use the 2to3 plugin, but something didn't work out to CRD. I originally created a strimzi-operator using helm3, the tiller cluster does not contain, when upgrading secret or cm, it gives the following errors.

When upgrading the operator itself:
```
helm 2to3 convert -n kafka strimzi-kafka                                                                   
2021/04/19 12:35:23 Release "strimzi-kafka" will be converted from Helm v2 to Helm v3.
2021/04/19 12:35:23 [Helm 3] Release "strimzi-kafka" will be created.
2021/04/19 12:35:23 Found 0 tiller pods
Error: plugin "2to3" exited with error
```
When upgrading secret:
```
helm 2to3 convert -n kafka strimzi-kafka --tiller-out-cluster -s secret sh.helm.release.v1.strimzi-kafka.v1                                            
Error: name of release to be converted has to be defined
Error: plugin "2to3" exited with error
```
or
```
helm 2to3 convert -n kafka strimzi-kafka -s secret sh.helm.release.v1.strimzi-kafka.v1 
Error: name of release to be converted has to be defined
Error: plugin "2to3" exited with error
```
Maybe there will be time to do this? I would like to somehow migrate crd from helm2 to helm3, so as not to affect the existing kafka cluster.

**Comment by runeanielsen** [comment]
@IlyaNakhaichuk I understand your frustration with the upgrade path of helm 2 to 3, but currently this is very low priority for this project, so I don't think I'll have time to look at it for a month or two. 

I think your best choice is try to ask in the issue https://github.com/strimzi/strimzi-kafka-operator/issues/3877 if anyone had the same issue as us.

**Comment by djok** [comment]
Hi,

Is there possible workaround for fresh installation. Downgrade to Helm 2 is not a option due to incompatibility with current versions of Kubernetes.

vbr,

**Comment by runeanielsen** [comment]
@djok currently we are running on version v1.17.13 of kubernetes, there are plans in the future to handle newer versions of kubernetes when this issue is fixed.

**Comment by djok** [comment]
@runeanielsen , can you tell me are you using public Kubernetes provider like GKE, Azure.... or you deploy on internal Kubernetes cluster. I ask this because so far I don't have success with deployment on GKE, and if you use public Kubernetes provider I can try to deploy on it.

**Comment by runeanielsen** [comment]
@djok we can run on all cloud providers, currently we are running our test setup Hetzner (personally managed) and customer on Azure(AKS). The setup is not "plug and play" and we're not done with the system yet and there might be major breaking changes in the near future, so we're not ready to write a setup guide.

**Comment by djok** [comment]
@runeanielsen, I will try to setup the project in AKS, can I count on some support during setup process?

**Comment by runeanielsen** [comment]
@djok its still not production ready, so I cannot help you with the setup - we don't recommend it being used with the current state of the project.

**Pull request closed without merging**
